apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: grpc-knative-cluster1
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
      - image: shahriarraka/simple-grpc-knative:latest
        ports:
        - name: h2c
          containerPort: 50051

